---
- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: "{{ extract_src_path }}/{{ item }}"
    dest: "{{ extract_dest_path }}"
    remote_src: yes
  with_items: "{{ unzip_file_list }}"
  register: unarchive


- debug: 
    msg: "{{ unarchive }}"
