- name: install depend pkg
  yum:
    name:
      - "{{ item }}"
    state: present
  with_items:
    - socat
    - conntrack

- name: swap off
  shell: "{{ item }}"
  with_items:
    - echo 0 > /proc/sys/vm/swappiness
    - swapoff -a
    - sed -i '/^[^ ]\+ \+swap \+/s/^/#/' /etc/fstab
    
- name: install k8s_install_pkg
  yum:
    name:
      - "{{ item }}-{{ version }}"
    state: present
  with_items:
    - kubelet
    - kubectl
    - kubeadm

- name: manage services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - docker
    - kubelet



