---
- name: Deploy virtual machine
  hosts: all
  tags:
    - deploy_vm
  gather_facts: false
  connection: local
  roles:
    - { role: deploy_vm }

- name: k8s environment
  hosts: all
  tags: k8s_env
  gather_facts: false
  become: yes
  become_user: root
  roles:
    - { role: k8s_env }

- name: k8s master node install
  hosts: all
  tags: k8s_master_install
  gather_facts: false
  become: yes
  become_user: root
  roles:
    - { role: k8s_master_install }

- name: k8s worker node join
  hosts: all
  tags: k8s_worker_join
  gather_facts: false
  become: yes
  become_user: root
  roles:
    - { role: k8s_worker_join }

- name: master init
  hosts: all
  tags: master_init
  gather_facts: false
  roles:
    - { role: k8s_master_init }

- name: create K8s folder
  hosts: all
  tags: create_k8s_folder
  gather_facts: false
  connection: local
  roles:
    - { role: create_k8s_folder }

- name: get K8s cert
  hosts: all
  tags: get_k8s_key
  gather_facts: false
  roles:
    - { role: get_k8s_key }

- name: deploy web terminal container
  hosts: terminal
  tags: deploy_terminal
  become: yes
  become_user: root
  gather_facts: false
  roles:
    - { role: deploy_terminal_container }