---
# defaults file for redhat.rebuildVMTemplate
# config modify
conf_modify:
  - path: /etc/ssh/sshd_config
    regexp: "^UseDNS"
    line: "UseDNS no"
  - path: /etc/ssh/sshd_config
    regexp: "^GSSAPIAuthentication"
    line: "GSSAPIAuthentication no"
  - path: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"

# yum repo setting
yum_repo:
  - name: chungyo
    file: chungyo
    baseurl: "http://192.168.104.131/repos/rhel/7plus/rhel-7-server-rpms/"
    gpgcheck: no
    enabled: yes
  - name: rhel-7-server-optional-rpms
    file: chungyo
    baseurl: "http://192.168.104.131/repos/rhel/7plus/rhel-7-server-optional-rpms/"
    gpgcheck: no
    enabled: yes
  - name: rhel-7-server-extras-rpms
    file: chungyo
    baseurl: "http://192.168.104.131/repos/rhel/7plus/rhel-7-server-extras-rpms/"
    gpgcheck: no
    enabled: yes
  - name: vmware-tools
    file: vmware-tools
    baseurl: "http://packages.vmware.com/packages/rhel7/x86_64/"
    gpgcheck: no
    enabled: yes

# yum setting
env_yum_packages:
  - name: net-snmp
    state: present
  - name: ntp
    state: present
  - name: open-vm-tools
    state: present
  - name: open-vm-tools-deploypkg
    state: present
  - name: net-tools
    state: present

# systemd setting
systemd_setting:
  - name: chronyd.service
    state: stopped
    enabled: no
  - name: postfix.service
    state: stopped
    enabled: no
  - name: tuned.service
    state: stopped
    enabled: no
  - name: rhsmcertd.service
    state: stopped
    enabled: no
  - name: ntpd.service
    state: started
    enabled: yes
  - name: snmpd.service
    state: started
    enabled: yes
  - name: sshd.service
    state: restarted
    enabled: yes
  - name: firewalld.service
    state: stopped
    enabled: no
  - name: vmtoolsd.service
    state: restarted
    enabled: yes

# sysctl setting
sysctl_setting:
  - name: "vm.swappiness"
    value: "30"
  - name: "net.ipv4.tcp_tw_recycle"
    value: "1"
  - name: "net.ipv4.tcp_tw_reuse"
    value: "1"
  - name: "net.core.netdev_max_backlog"
    value: "65535"
  - name: "net.ipv4.tcp_max_syn_backlog"
    value: "65535"
  - name: "net.core.somaxconn"
    value: "65535"

# PAM limits  setting
hardening_ulimit:
  - domain: root
    type: '-'
    item: nproc
    value: 65535
  - domain: root
    type: '-'
    item: nofile
    value: 65535
  - domain: root
    type: '-'
    item: core
    value: 102400

# copy hosts allow and deny
copy_hosts_rule_list:
  - hosts.allow
  - hosts.deny

# add ssh authorized key
ssh_authorized:
  - userdir: /root
    pubkey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCuGjBfCJlbp/xe4s7PGeCB+QLMiyEBrkAnmqyRya661C9gF4vSEFfC3BDXmgJrAbOBe93YK7DBpwbvgTIWrjcA207sJKCyxmSEjyyzYVWmB6ccRRApMEyf74NtD8Ri3kI7GtA/A6PG7FTgPdYnBSn6fEa3HoBr9u7g9GT09QFi77E4xboK1KR/8cv/rq1vQRLmKTX/pdFoSqs4ocod1OhMPIOPcZjz5uUlX7U0aGdD9b3KUPIY/9eaAX6UR1w+Q0dNf109wourG2fLHPFlfDHN4ax+kKTEYUW4tzIZfKX7IAuMZmMsSCYRyExdBZVFW2Oj/EaKSA9gclrOgm+Ier7b jack@ansible02.rd.apes.com.tw'

# add users
add_user_list:
  - name: sys-admin
  - name: op-admin
    password: '$6$rgIDF5uR10Y3O924$qmcTJeXevNoiPs2LEx6x82twouUTCbZsGZK7MruKZjvEi6cUyDiO4pO2Oiqo1RCR4fSA2cB9C9Tjdrzui5pmo.'
  - name: api
    password: '$6$rgIDF5uR10Y3O924$qmcTJeXevNoiPs2LEx6x82twouUTCbZsGZK7MruKZjvEi6cUyDiO4pO2Oiqo1RCR4fSA2cB9C9Tjdrzui5pmo.'
  - name: root
    password: '$6$rgIDF5uR10Y3O924$qmcTJeXevNoiPs2LEx6x82twouUTCbZsGZK7MruKZjvEi6cUyDiO4pO2Oiqo1RCR4fSA2cB9C9Tjdrzui5pmo.'
  
# copy role files
copy_role_file_list:
  - apr-1.5.2.tar.gz
  - apr-util-1.5.4.tar.gz
  - httpd-2.2.24.tar.gz
  - libmcrypt-2.5.8-9.el6.x86_64.rpm
  - libmcrypt-devel-2.5.8-9.el6.x86_64.rpm
  - php-7.0.9.tar.xz
copy_role_file_dest_path: '/tmp'
#copy local files
local_file_path: []
dest_file_path: []
copy_local_file_list: []

#Unarchive a file that is already on the remote machine
extract_src_path: /tmp
extract_dest_path: /tmp
unzip_file_list:
  - apr-1.5.2.tar.gz
  - apr-util-1.5.4.tar.gz
  - httpd-2.2.24.tar.gz
  - php-7.0.9.tar.xz
#Ensure packages or dependencies installed.
yum_packages:
  - openssl-devel
  - perl*
  - httpd-devel
  - libxml2
  - libxml2-devel
  - curl-devel
  - libjpeg-turbo
  - libjpeg-turbo-devel
  - libpng-devel
  - freetype
  - freetype-devel
  - icu
  - libicu
  - libicu-devel
  - gcc #extra
  - /tmp/libmcrypt-2.5.8-9.el6.x86_64.rpm
  - /tmp/libmcrypt-devel-2.5.8-9.el6.x86_64.rpm
packages_state: present

#configure and make install
source_file_path: /tmp
rebuild_packages:
  - name: apr-1.5.2
    src_name: apr-1.5.2.tar.gz
    configure_command: >
      ./configure --prefix=/usr/local/apr
    
  - name: apr-util-1.5.4
    src_name: apr-util-1.5.4.tar.gz
    configure_command: >
      ./configure --prefix=/usr/local/apr-util 
      -with-apr=/usr/local/apr/bin/apr-1-config 

  - name: httpd-2.2.24
    src_name: httpd-2.2.24.tar.gz
    configure_command: >
      ./configure --prefix=/usr/local/web/apache2  
      --with-apr=/usr/local/apr 
      --with-apr-util=/usr/local/apr-util 
      --with-libxml2=/usr/local/libxml2 
      --enable-so 
      --enable-cgi 
      --enable-rewrite 
      --with-mpm=prefork 
      --enable-cache 
      --enable-headers 
      --enable- 
      --enable-rewrite 
      --enable-alias 
      --enable-ssl 
      --enable-static-rotatelogs 
      --enable-static-logresolve

  - name: php-7.0.9
    src_name: php-7.0.9.tar.xz
    configure_command: >
      ./configure --prefix=/usr/local/web/php/source/7.0.9 
      --with-config-file-path=/usr/local/web/php/source/7.0.9 
      --with-apxs2=/usr/local/web/apache2/bin/apxs 
      --with-mcrypt 
      --with-openssl 
      --with-mysql-sock 
      --with-gd 
      --with-jpeg-dir=/usr/lib 
      --with-curl 
      --with-iconv 
      --with-gettext 
      --with-freetype-dir=/usr 
      --with-fpm-user=nobody 
      --with-fpm-group=nobody 
      --with-pdo-mysql=mysqlnd 
      --with-mysqli=mysqlnd 
      --enable-mbstring 
      --enable-fpm 
      --enable-gd-native-ttf 
      --enable-zip 
      --enable-sockets 
      --enable-intl 
      --enable-pcntl 
      --enable-tokenizer 
      --enable-sysvshm 
      --enable-sysvsem 
      --enable-standard 
      --enable-Reflection 
      --enable-SPL 
      --enable-sqlite3 
      --with-zlib

# Setup SOE tasks.
action_base_env: true
# Setup SOE with PHP tasks
action_copy_from_source: true
action_extract_files: true
action_yum_install: true
action_install_packages: true
