---
# tasks file for deploy_terminal_container
- name: deploy
  shell: "docker run -d --name={{ dept }}-{{ clusterID }} -v /home/sys-admin/k8s_config/{{ dept }}/{{ clusterID }}:/home/ces -p {{ port }}:8080 -h {{ dept }}-{{ clusterID }} ces-terminal:v5 ces:{{ pass }} bash"