---
# tasks file for deploy_terminal_container
- name: deploy terminal
  shell: "docker run -d --name={{ dept }}-{{ clusterID }} -v /home/sys-admin/k8s_config/{{ dept }}/{{ clusterID }}:/home/ces -p {{ port }}:8080 -h {{ dept }}-{{ clusterID }} 172.16.99.240:5000/ces-terminal:v5 ces:{{ pass }} bash"